[workspace]
members = [
	"contract-address",
	"fixed-hash",
	"keccak-hash",
	"kvdb",
	"kvdb-memorydb",
	"kvdb-rocksdb",
	"kvdb-web",
	"parity-bytes",
	"parity-crypto",
	"parity-path",
	"plain_hasher",
	"rlp",
	"transaction-pool",
	"trace-time",
	"triehash",
	"uint",
	"parity-util-mem",
	"primitive-types",
	"ethereum-types",
	"ethbloom",
]

[patch.crates-io]
secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1.git", branch = "dp/chore/update-to-upstream"}
#secp256k1 = { path = "../parity-secp256k1" }

